raw_data_schema:
  required_columns:
    - TransactionAmount
    - TransactionType
    - Location
    - MerchantID
    - Channel
    - CustomerAge
    - CustomerOccupation
    - TransactionDuration
    - LoginAttempts
    - AccountBalance

  numerical_columns:
    - TransactionAmount
    - CustomerAge
    - TransactionDuration
    - LoginAttempts
    - AccountBalance

  categorical_columns:
    - TransactionType
    - Location
    - Channel
    - CustomerOccupation
    - MerchantID

  drop_columns:
    - TransactionID
    - AccountID
    - DeviceID
    - IP Address 
    
processed_data_schema:
  required_columns:
    - TransactionAmount
    - CustomerAge
    - TransactionDuration
    - LoginAttempts
    - AccountBalance
    - TransactionYear              
    - TransactionMonth             
    - TransactionDay               
    - TransactionHour   
    - PrevTransactionYear          
    - PrevTransactionMonth         
    - PrevTransactionDay           
    - PrevTransactionHour
    - TransactionType 
    - Location            
    - MerchantID      
    - Channel      
    - CustomerOccupation

  numerical_columns:
    - TransactionAmount
    - CustomerAge
    - TransactionDuration
    - LoginAttempts
    - AccountBalance
    - TransactionYear              
    - TransactionMonth             
    - TransactionDay               
    - TransactionHour   
    - PrevTransactionYear          
    - PrevTransactionMonth         
    - PrevTransactionDay           
    - PrevTransactionHour

  categorical_columns:
    - TransactionType 
    - Location            
    - MerchantID      
    - Channel      
    - CustomerOccupation
